// <auto-generated />
using System;
using IoTSuper_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IoTSuper_API.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260513170303_creacionTablasClienteTipoLoca3")]
    partial class creacionTablasClienteTipoLoca3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IoTSuper_API.Models.Centro", b =>
                {
                    b.Property<int>("IdCentro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_centro");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCentro"));

                    b.Property<string>("Cif")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cif");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("habilitado");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdLocalizacion")
                        .HasColumnType("int")
                        .HasColumnName("id_localizacion");

                    b.Property<int>("IdTipologia")
                        .HasColumnType("int")
                        .HasColumnName("id_tipologia");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("imagen");

                    b.Property<int>("LocalizacionIdLocalizacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("razon_social");

                    b.Property<int>("TipologiaIdTipologia")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("IdCentro");

                    b.HasIndex("LocalizacionIdLocalizacion");

                    b.HasIndex("TipologiaIdTipologia");

                    b.ToTable("Centros");
                });

            modelBuilder.Entity("IoTSuper_API.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("apellido");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contraseña");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("empresa");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("esAdmin");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("habilitado");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("login");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Totp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("totp");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("IoTSuper_API.Models.Localizacion", b =>
                {
                    b.Property<int>("IdLocalizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_localizacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLocalizacion"));

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("pais");

                    b.Property<string>("provincia")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Provincia");

                    b.HasKey("IdLocalizacion");

                    b.ToTable("Localizaciones");
                });

            modelBuilder.Entity("IoTSuper_API.Models.Tipologia", b =>
                {
                    b.Property<int>("IdTipologia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipologia");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipologia"));

                    b.Property<string>("TipoTienda")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_tienda");

                    b.HasKey("IdTipologia");

                    b.ToTable("Tipologias");
                });

            modelBuilder.Entity("IoTSuper_API.Models.Centro", b =>
                {
                    b.HasOne("IoTSuper_API.Models.Localizacion", "Localizacion")
                        .WithMany("Centros")
                        .HasForeignKey("LocalizacionIdLocalizacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IoTSuper_API.Models.Tipologia", "Tipologia")
                        .WithMany("Centros")
                        .HasForeignKey("TipologiaIdTipologia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localizacion");

                    b.Navigation("Tipologia");
                });

            modelBuilder.Entity("IoTSuper_API.Models.Localizacion", b =>
                {
                    b.Navigation("Centros");
                });

            modelBuilder.Entity("IoTSuper_API.Models.Tipologia", b =>
                {
                    b.Navigation("Centros");
                });
#pragma warning restore 612, 618
        }
    }
}
