<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Estilos\Fuentes\Manrope-VariableFont_wght.ttf" />
    <None Remove="Estilos\Iconos\candado.png" />
    <None Remove="Estilos\Iconos\centros.png" />
    <None Remove="Estilos\Iconos\edit.png" />
    <None Remove="Estilos\Iconos\exit.png" />
    <None Remove="Estilos\Iconos\incidencias.png" />
    <None Remove="Estilos\Iconos\inicio.png" />
    <None Remove="Estilos\Iconos\iot.png" />
    <None Remove="Estilos\Iconos\left.png" />
    <None Remove="Estilos\Iconos\lupa.png" />
    <None Remove="Estilos\Iconos\nuevo.png" />
    <None Remove="Estilos\Iconos\qr.png" />
    <None Remove="Estilos\Iconos\right.png" />
    <None Remove="Estilos\Iconos\scanner.png" />
    <None Remove="Estilos\Iconos\trash.png" />
    <None Remove="Estilos\Iconos\user.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Abstractions" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Extensions" Version="10.0.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Otp.NET" Version="1.4.1" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Estilos\Fuentes\Manrope-VariableFont_wght.ttf" />
    <Resource Include="Estilos\Iconos\candado.png" />
    <Resource Include="Estilos\Iconos\centros.png" />
    <Resource Include="Estilos\Iconos\edit.png" />
    <Resource Include="Estilos\Iconos\exit.png" />
    <Resource Include="Estilos\Iconos\incidencias.png" />
    <Resource Include="Estilos\Iconos\inicio.png" />
    <Resource Include="Estilos\Iconos\iot.png" />
    <Resource Include="Estilos\Iconos\left.png" />
    <Resource Include="Estilos\Iconos\lupa.png" />
    <Resource Include="Estilos\Iconos\nuevo.png" />
    <Resource Include="Estilos\Iconos\qr.png" />
    <Resource Include="Estilos\Iconos\right.png" />
    <Resource Include="Estilos\Iconos\scanner.png" />
    <Resource Include="Estilos\Iconos\trash.png" />
    <Resource Include="Estilos\Iconos\user.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Vistas\Cliente\" />
  </ItemGroup>

</Project>
